In [2]:
import numpy as np
a = [1,2,3]
b=np.array(a)
type(b)

numpy.ndarray

In [8]:
a =[1,2,3,4,4.5]
b=np.array(a , dtype=int)
print(b)

[1 2 3 4 4]


In [10]:
a =[1,2,3,'4',4.5]
b=np.array(a *3)
print(b)

['1' '2' '3' '4' '4.5' '1' '2' '3' '4' '4.5' '1' '2' '3' '4' '4.5']


In [12]:
b = np.ones(3,dtype = int)
b

array([1, 1, 1])

In [16]:
b = np.ones(3,dtype = int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
b = np.full(3,fill_value=4.4)
type(b[0])

numpy.float64

In [36]:
c = np.empty(8,dtype=int)
c

array([      0,       1,       0, 5570652,    1424,       0,     768,
           127])

In [16]:
import numpy as np
tdlist = [[1,2,3],[3,4,5],[5,6,7]]

b = np.array(tdlist)
print((b))

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [19]:
import numpy as np
b=np.zeros(10,dtype=int)
b[4] = 1
b


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [23]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [25]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b = np.linspace(2,10,5)
b
print(b[1] -b[0])
b

2.0


array([ 2.,  4.,  6.,  8., 10.])

In [35]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
b = np.random.rand(3,4)
b

array([[0.95011726, 0.99147821, 0.09456787, 0.06245872],
       [0.1660931 , 0.29969795, 0.55073132, 0.94819033],
       [0.66917399, 0.12096911, 0.72937572, 0.35727663]])

In [114]:
b = np.random.rand(3,2)*10
b

array([[7.68950581, 7.79650803],
       [5.60753989, 9.42808923],
       [8.03431073, 3.67520309]])

In [149]:
b = np.random.randint(0,100)*10
b

570

In [163]:
b = np.random.randint(10 ,size=(3,3))*10
b

array([[30, 80, 50],
       [90, 50,  0],
       [80, 10, 50]])

In [165]:
c = np.arange(9,50)
c

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [170]:
r = np.linspace(0,5,10,float)
r

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [4]:
import numpy as np
ls= [1,2,3,4,5]
arr = np.array(ls)
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [7]:
print(ls[2])
print(arr[3])
print(arr[1:3])

3
4
[2 3]


In [8]:
import numpy as np
ls2= [[1,2,3],[3,4,5] , [4,3,4]]
arr2 = np.array(ls2)
print(arr2.data)
print(arr2.shape)
print(arr2.dtype)
print(arr2.strides)

(3, 3)
int32
(12, 4)


In [12]:
print(ls2)
print(arr2[2,1])
# also use comma for retriving an element

[[1, 2, 3], [3, 4, 5], [4, 3, 4]]
3


In [15]:
# slice element from 2 d array
print(ls2[1][:3])
print(arr2[1][:3])

[3, 4, 5]
[3 4 5]


In [17]:
print(ls2[0:3][2])

[4, 3, 4]


In [18]:
print(arr2[0:3 , 2])

[3 5 4]


In [1]:
import numpy as np
ls = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
print(ls)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 3 14  4  6 18]
[10  3  5  6 16]


In [2]:
ls = [i+1 for i in ls]
ls

[2, 3, 4, 5, 6]

In [5]:
a = a+1
a

array([ 6, 17,  7,  9, 21])

In [6]:
c = a+b

In [7]:
c

array([16, 20, 12, 15, 37])

In [8]:
c = a-b
c

array([-4, 14,  2,  3,  5])

In [9]:
h = a ** b
h

array([ 60466176,      4913,     16807,    531441, 492582081], dtype=int32)

In [13]:
print(a)

print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())

[ 6 17  7  2 21]
53
10.6
2
3


In [14]:
print(a)
print(b)
a>b

[ 6 17  7  2 21]
[10  3  5  6 16]


array([False,  True,  True, False,  True])

In [17]:
a[2] =0
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[ True  True  True  True  True]
[ True  True False  True  True]
[0 0 1 0 0]


In [22]:
import numpy as np

b = np.random.randint(1,20,8)
print(b)
print(b >10)

[17  1 10 14 11  7  5  6]
[ True False False  True  True False False False]


In [24]:
bool_arr = b>10
print(bool_arr)
new_ar = b[bool_arr]
print(new_ar)

[ True False False  True  True False False False]
[17 14 11]


In [25]:
n = b[b>10]
print(n)

[17 14 11]


In [51]:
b = np.random.randint(1,20,8)
c = b
c[:3] = 9
c[c>10] =10
# print(b)
print(c)

[ 9  9  9 10 10 10  9 10]


In [53]:
print(b[b==10])

[10 10 10 10]


In [54]:
ind  = np.where(b ==10)
ind

(array([3, 4, 5, 7], dtype=int64),)

In [61]:
a  = ['t','a','m','d','h','w']
print(a)
print(b)

['t', 'a', 'm', 'd', 'h', 'w']
[ 9  9  9 10 10 10  9 10]


In [68]:
ind  = np.where(b == 10)
print(ind)
print([ind])

(array([3, 4, 5, 7], dtype=int64),)
[(array([3, 4, 5, 7], dtype=int64),)]


In [11]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[16 10 15 19  1  2]
 [21  8 17 25 19 20]
 [ 9 28  8  8 21  5]
 [ 3  9 21 12 22 20]
 [ 8 22 20 13  1 10]]


In [14]:
booltf =a >20
booltf

array([[False, False, False, False, False, False],
       [ True, False, False,  True, False, False],
       [False,  True, False, False,  True, False],
       [False, False,  True, False,  True, False],
       [False,  True, False, False, False, False]])

In [17]:
boolarr = a[booltf]
print(boolarr)
b = a

[21 25 28 21 21 22 22]


In [27]:
b[booltf] =100
b[1][1] =123
print(b)

[[ 16  10  15  19   1   2]
 [100 123  99 100  99  99]
 [  9 100   8   8 100   5]
 [  3   9 100  12 100  20]
 [  8 100  20  13   1  10]]


In [28]:
bool_arr =b[:,3] ==100
print(bool_arr)
b[bool_arr,3] = 99
print(b)

[False  True False False False]
[[ 16  10  15  19   1   2]
 [100 123  99  99  99  99]
 [  9 100   8   8 100   5]
 [  3   9 100  12 100  20]
 [  8 100  20  13   1  10]]


In [30]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)


[[2 4 5]
 [9 3 1]
 [7 9 4]]
[[8 1 8]
 [8 8 3]
 [6 9 3]]


In [31]:
ans = x - y
print(ans)

[[-6  3 -3]
 [ 1 -5 -2]
 [ 1  0  1]]


In [32]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)


[[2 8 2]
 [7 3 5]
 [8 1 6]]
[3 3 4]


In [33]:
ans = x - y
print(ans)

[[-1  5 -2]
 [ 4  0  1]
 [ 5 -2  2]]


In [36]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
y=np.transpose(y)
print(x)
print(y)
ans = x - y
print(ans)

[[3 1]
 [7 9]
 [9 6]]
[[6 4]
 [6 7]
 [5 8]]
[[-3 -3]
 [ 1  2]
 [ 4 -2]]


Also use to make different size array compatible ->
1.resize
2.reshape